# fly.toml app configuration file generated for albatross-2025 on 2025-06-27T00:12:06+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'albatross-2025'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = "python manage.py migrate --no-input"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true  # ← true/false で指定
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s" # ← 念のため、猶予期間は、長めに！
    method = "GET"
    path = "/accounts/login/" # ログインページを、チェック
    protocol = "http"
