"""
Django settings for albatross project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import re
from django.urls import reverse_lazy
DEBUG = os.environ.get("FLY_APP_NAME") is None

# 5/9---osモジュールを使うためにosをインポート追記
# 5/22---reverse_lazy追加
# 6/24---ポスグレSQLに変えるためのDJDATEBASEURL


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ez#l2(hhk9bx9cm*r9nvt8-#&2@7_=-ulpnzvs24jjq*6vjxv9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
# ALLOWED_HOSTSに、Fly.ioのアプリのURLを追加する
# 今は、'albatross-2025.fly.dev' っていうのが、マサ君のアプリの住所だね！
ALLOWED_HOSTS = ['albatross-2025.fly.dev', 'localhost', '127.0.0.1']

# Application definition

# 5/9...アロードホストを空欄から上記に変更「今まさに使ってる、この自分のパソコン」 を指す特別な名前と住所



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "accounts",
    "logs",
    "albatross_app",
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'albatross.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'albatross.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# ▼▼▼ DATABASESの設定を、これにまるっと書き換える！ ▼▼▼
# まずは、ローカル用のSQLiteの設定を、デフォルトとして書いておく
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 本番環境（Fly.io）で、DATABASE_URLが設定されてる場合の、特別な処理
if 'DATABASE_URL' in os.environ:
    # Fly.ioが提供するDATABASE_URLを、正規表現で、部品ごとに分解する！
    database_url = os.environ['DATABASE_URL']
    match = re.match(r'postgres://(.*?):(.*?)@(.*?):(.*?)/(.*)', database_url)
    
    # ★★★ もし、分解がうまくいかなかった時のための、安全装置を追加！ ★★★
    if match:
        db_user = match.group(1)
        db_password = match.group(2)
        db_host = match.group(3)
        db_port = match.group(4)
        db_name = match.group(5)

        # 分解した部品を使って、PostgreSQLの設定を、自分たちの手で、完全に作り直す！
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
            'OPTIONS': {'sslmode': 'require'},
        }
    else:
        # もし、URLの分解に失敗したら、エラーを出すようにする
        raise ValueError("DATABASE_URLの解析に失敗しました。")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True

# 5/9...言語は日本語に変更
# 5/9...タイムゾーンはアジア東京に変更


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# 5/9...Djangoプロジェクト内のあちこちにある静的ファイルを、一箇所に集めるためのフォルダの場所を指定する


LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "albatross_app:chart_type_list"
LOGOUT_REDIRECT_URL = reverse_lazy("accounts:login")

# 1 これは urls.py で name='login' って付けた名前を指定
# 2 ログイン成功したらトップページ / に飛ばすよ、って意味。
# 2 もしログイン後にチャート選択画面とかに直接飛ばしたいなら、そのURLに変える！
# 3 ログアウトしたら、name='login' のページ（つまりログインページ）に飛ばすよ、って意味。
# "/"からreverse_lazy("accounts:login")に変更、明示的に飛ばす。
# ↑↑↑ 'albatross_app' (アプリ名) と 'chart_type_list' (さっき付けたURL名) を指定！


# CSRF_TRUSTED_ORIGINSも設定しとくと、より安全！
CSRF_TRUSTED_ORIGINS = ['https://albatross-2025.fly.dev']