# Generated by Django 4.2.2 on 2025-05-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quewtion_text', models.TextField(verbose_name='質問文')),
                ('is_starting_step', models.BooleanField(default=False, verbose_name='開始ステップか')),
                ('is_final_step', models.BooleanField(default=False, verbose_name='最終ステップか')),
                ('solution_text', models.TextField(blank=True, null=True, verbose_name='解決策/メッセージ')),
                ('no_next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goes_to_no', to='albatross_app.chartstep', verbose_name='「いいえ」の場合の次のステップ')),
                ('yes_next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goes_to_yes', to='albatross_app.chartstep', verbose_name='「はい」次のステップ')),
            ],
            options={
                'verbose_name': 'チャートステップ',
                'verbose_name_plural': 'チャートステップ',
            },
        ),
    ]
