# Generated by Django 5.2.3 on 2025-09-06 16:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='チャート種別名')),
                ('description', models.TextField(blank=True, verbose_name='チャート種別の説明')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='albatross_app.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': 'チャート種別',
                'verbose_name_plural': 'チャート種別',
            },
        ),
        migrations.CreateModel(
            name='ChartStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_beginner', models.TextField(blank=True, verbose_name='質問文（初級）')),
                ('question_text_intermediate', models.TextField(blank=True, verbose_name='質問文（中級）')),
                ('is_starting_step', models.BooleanField(default=False, verbose_name='開始ステップか')),
                ('is_final_step', models.BooleanField(default=False, verbose_name='最終ステップか')),
                ('solution_text', models.TextField(blank=True, null=True, verbose_name='解決策/メッセージ')),
                ('detailed_explanation', models.TextField(blank=True, verbose_name='詳細解説（アコーディオン用）')),
                ('solution_type', models.CharField(blank=True, choices=[('improved', '解決/改善'), ('unresolved', '未解決/改善なし'), ('info', '情報/その他')], default=None, max_length=20, null=True, verbose_name='解決タイプ')),
                ('keyword_advanced', models.CharField(blank=True, max_length=100, verbose_name='キーワード（上級）')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='low', max_length=10, verbose_name='リスクレベル（上級）')),
                ('display_order', models.IntegerField(default=0, help_text='数字が小さいものから順に表示されます。', verbose_name='表示順序（上級）')),
                ('no_next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goes_to_no', to='albatross_app.chartstep', verbose_name='「いいえ」の場合の次のステップ')),
                ('yes_next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goes_to_yes', to='albatross_app.chartstep', verbose_name='「はい」次のステップ')),
                ('chart_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albatross_app.charttype', verbose_name='チャート種別')),
            ],
            options={
                'verbose_name': 'チャートステップ',
                'verbose_name_plural': 'チャートステップ',
            },
        ),
        migrations.CreateModel(
            name='TroubleshootingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='完了日時')),
                ('is_resolved', models.BooleanField(default=True, verbose_name='解決済みフラグ')),
                ('chart_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albatross_app.charttype', verbose_name='チャート種別')),
                ('resolved_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='albatross_app.chartstep', verbose_name='解決ステップ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'トラブルシューティングセッション',
                'verbose_name_plural': 'トラブルシューティングセッション',
                'ordering': ['-end_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'はい'), ('no', 'いいえ'), ('unknown', '不明')], max_length=10, verbose_name='回答')),
                ('chart_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albatross_app.chartstep', verbose_name='チャートステップ')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='albatross_app.troubleshootingsession', verbose_name='セッション')),
            ],
            options={
                'verbose_name': 'セッションログ',
                'verbose_name_plural': 'セッションログ',
                'unique_together': {('session', 'chart_step')},
            },
        ),
    ]
