# Generated by Django 4.2.2 on 2025-05-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albatross_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='チャート種別名')),
                ('descriotion', models.TextField(blank=True, verbose_name='チャート種別の説明')),
            ],
            options={
                'verbose_name': 'チャート種別',
                'verbose_name_plural': 'チャート種別',
            },
        ),
    ]
