# Generated by Django 5.2.3 on 2025-10-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albatross_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ枠', 'verbose_name_plural': 'カテゴリ枠'},
        ),
        migrations.AlterModelOptions(
            name='chartstep',
            options={'verbose_name': 'チャート内容', 'verbose_name_plural': 'チャート内容'},
        ),
        migrations.AlterModelOptions(
            name='charttype',
            options={'verbose_name': '故障項目ボタン', 'verbose_name_plural': '故障項目ボタン'},
        ),
        migrations.AlterModelOptions(
            name='sessionlog',
            options={'verbose_name': 'セッションログ（子）', 'verbose_name_plural': 'セッションログ（子）'},
        ),
        migrations.AlterModelOptions(
            name='troubleshootingsession',
            options={'ordering': ['-end_time'], 'verbose_name': 'トラブルシューティングセッション（親）', 'verbose_name_plural': 'トラブルシューティングセッション（親）'},
        ),
    ]
