# Generated by Django 4.2.2 on 2025-05-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albatross_app', '0002_charttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartstep',
            old_name='quewtion_text',
            new_name='question_text',
        ),
    ]
