# Generated by Django 5.2.3 on 2026-01-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albatross_app', '0002_alter_category_options_alter_chartstep_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartstep',
            options={'ordering': ['display_order'], 'verbose_name': 'チャート内容', 'verbose_name_plural': 'チャート内容'},
        ),
        migrations.AlterModelOptions(
            name='sessionlog',
            options={'ordering': ['chart_step__display_order'], 'verbose_name': 'セッションログ（子）', 'verbose_name_plural': 'セッションログ（子）'},
        ),
    ]
