# Generated by Django 4.2.2 on 2025-05-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albatross_app', '0003_rename_quewtion_text_chartstep_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstep',
            name='chart_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='albatross_app.charttype', verbose_name='チャート種別'),
            preserve_default=False,
        ),
    ]
