# Generated by Django 4.2.2 on 2025-05-28 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albatross_app', '0004_chartstep_chart_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleshootingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='完了日時')),
                ('chart_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albatross_app.charttype', verbose_name='チャート種別')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'トラブルシューティングセッション',
                'verbose_name_plural': 'トラブルシューティングセッション',
                'ordering': ['-end_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'はい'), ('no', 'いいえ'), ('unknown', '不明')], max_length=10, verbose_name='回答')),
                ('chart_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albatross_app.chartstep', verbose_name='チャートステップ')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='albatross_app.troubleshootingsession', verbose_name='セッション')),
            ],
            options={
                'verbose_name': 'セッションログ',
                'verbose_name_plural': 'セッションログ',
                'unique_together': {('session', 'chart_step')},
            },
        ),
    ]
