# Generated by Django 4.2.2 on 2025-06-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albatross_app', '0005_troubleshootingsession_sessionlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charttype',
            old_name='descriotion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='chartstep',
            name='solution_type',
            field=models.CharField(blank=True, choices=[('improved', '解決/改善'), ('unresolved', '未解決/改善なし'), ('info', '情報/その他')], default=None, max_length=20, null=True, verbose_name='解決タイプ'),
        ),
    ]
