# Generated by Django 4.2.2 on 2025-06-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albatross_app', '0006_rename_descriotion_charttype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstep',
            name='keyword_advanced',
            field=models.CharField(blank=True, max_length=100, verbose_name='キーワード（上級）'),
        ),
        migrations.AddField(
            model_name='chartstep',
            name='risk_level',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='low', max_length=10, verbose_name='リスクレベル（上級）'),
        ),
        migrations.AlterField(
            model_name='chartstep',
            name='question_text',
            field=models.TextField(verbose_name='質問文（中級）'),
        ),
    ]
