# Generated by Django 4.2.2 on 2025-06-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albatross_app', '0007_chartstep_keyword_advanced_chartstep_risk_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartstep',
            name='question_text',
        ),
        migrations.AddField(
            model_name='chartstep',
            name='display_order',
            field=models.IntegerField(default=0, help_text='数字が小さいものから順に表示されます。', verbose_name='表示順序（上級）'),
        ),
        migrations.AddField(
            model_name='chartstep',
            name='question_text_beginner',
            field=models.TextField(blank=True, verbose_name='質問文（初級）'),
        ),
        migrations.AddField(
            model_name='chartstep',
            name='question_text_intermediate',
            field=models.TextField(blank=True, verbose_name='質問文（中級）'),
        ),
    ]
