# Generated by Django 5.2.3 on 2025-06-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albatross_app', '0008_remove_chartstep_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartstep',
            name='detailed_explanation',
            field=models.TextField(blank=True, verbose_name='詳細解説（アコーディオン用）'),
        ),
    ]
