# Generated by Django 5.2.1 on 2025-07-01 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albatross_app', '0009_chartstep_detailed_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleshootingsession',
            name='is_resolved',
            field=models.BooleanField(default=True, verbose_name='解決済みフラグ'),
        ),
        migrations.AddField(
            model_name='troubleshootingsession',
            name='resolved_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='albatross_app.chartstep', verbose_name='解決ステップ'),
        ),
    ]
