# Generated by Django 5.2.3 on 2025-09-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albatross_app', '0010_troubleshootingsession_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charttype',
            name='category',
            field=models.CharField(choices=[('power', '電源'), ('function', '機能'), ('network', '光'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
